-- Generated by nwg-displays on 2026-09-27 at 23:51:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@165.0",
    position = "3280x0",
    scale = 2.000000000000001,
    vrr = 0
})
