# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(070000)
$foreground = rgb(DDE7E6)
$color0 = rgb(1E1A17)
$color1 = rgb(456980)
$color2 = rgb(456980)
$color3 = rgb(49697C)
$color4 = rgb(6C6963)
$color5 = rgb(8A694D)
$color6 = rgb(768C8B)
$color7 = rgb(C6D4D4)
$color8 = rgb(8A9494)
$color9 = rgb(5C8CAA)
$color10 = rgb(5C8CAA)
$color11 = rgb(628CA6)
$color12 = rgb(908C84)
$color13 = rgb(B88C66)
$color14 = rgb(9DBAB9)
$color15 = rgb(C6D4D4)

# Translucent accents used by floating-window shadows.
$shadow_active = rgba(908C8466)
$shadow_inactive = rgba(5C8CAA2E)
