# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(3F3F3F)
$foreground = rgb(DCDCCC)
$color0 = rgb(3F3F3F)
$color1 = rgb(DCA3A3)
$color2 = rgb(5F7F5F)
$color3 = rgb(E0CF9F)
$color4 = rgb(7CB8BB)
$color5 = rgb(DC8CC3)
$color6 = rgb(93E0E3)
$color7 = rgb(DCDCCC)
$color8 = rgb(4F4F4F)
$color9 = rgb(DCA3A3)
$color10 = rgb(5F7F5F)
$color11 = rgb(E0CF9F)
$color12 = rgb(7CB8BB)
$color13 = rgb(DC8CC3)
$color14 = rgb(93E0E3)
$color15 = rgb(FFFFFF)

# Translucent accents used by floating-window shadows.
$shadow_active = rgba(7CB8BB66)
$shadow_inactive = rgba(5F7F5F2E)
