# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1A1D)
$foreground = rgb(E2DAEC)
$color0 = rgb(424044)
$color1 = rgb(17111F)
$color2 = rgb(1E1726)
$color3 = rgb(4C405B)
$color4 = rgb(514272)
$color5 = rgb(746388)
$color6 = rgb(816F97)
$color7 = rgb(CDC1DC)
$color8 = rgb(90879A)
$color9 = rgb(1F1729)
$color10 = rgb(281F33)
$color11 = rgb(665579)
$color12 = rgb(6C5898)
$color13 = rgb(9A84B5)
$color14 = rgb(AC94C9)
$color15 = rgb(CDC1DC)

# Translucent accents used by floating-window shadows.
$shadow_active = rgba(6C589866)
$shadow_inactive = rgba(281F332E)
