# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DCDCCC
background         #3F3F3F
cursor             #DCDCCC

active_tab_foreground     #3F3F3F
active_tab_background     #DCDCCC
inactive_tab_foreground   #DCDCCC
inactive_tab_background   #3F3F3F

active_border_color   #DCDCCC
inactive_border_color #3F3F3F
bell_border_color     #DCA3A3

color0      #3F3F3F
color1		#DCA3A3
color2		#5F7F5F
color3		#E0CF9F
color4		#7CB8BB
color5		#DC8CC3
color6		#93E0E3
color7		#DCDCCC
color8		#4F4F4F
color9		#DCA3A3
color10		#5F7F5F
color11		#E0CF9F
color12		#7CB8BB
color13		#DC8CC3
color14		#93E0E3
color15		#FFFFFF
