# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DBEDD0
background         #151718
cursor             #7B9085

active_tab_foreground     #151718
active_tab_background     #DBEDD0
inactive_tab_foreground   #DBEDD0
inactive_tab_background   #151718

active_border_color   #DBEDD0
inactive_border_color #151718
bell_border_color     #14252A

color0      #3C3E3F
color1		#14252A
color2		#15262C
color3		#15262C
color4		#3D554C
color5		#436C4F
color6		#72995B
color7		#C3DDB4
color8		#899B7E
color9		#1B3138
color10		#1C333A
color11		#1C333A
color12		#517165
color13		#5A906A
color14		#98CC7A
color15		#C3DDB4
