# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2DAEC
background         #1C1A1D
cursor             #857C90

active_tab_foreground     #1C1A1D
active_tab_background     #E2DAEC
inactive_tab_foreground   #E2DAEC
inactive_tab_background   #1C1A1D

active_border_color   #E2DAEC
inactive_border_color #1C1A1D
bell_border_color     #17111F

color0      #424044
color1		#17111F
color2		#1E1726
color3		#4C405B
color4		#514272
color5		#746388
color6		#816F97
color7		#CDC1DC
color8		#90879A
color9		#1F1729
color10		#281F33
color11		#665579
color12		#6C5898
color13		#9A84B5
color14		#AC94C9
color15		#CDC1DC
